### PR TITLE
Improve guessing the download filename

### LINKED ISSUE #11: Automated snap builds have stopped working
The current version of [codium on Snapcraft](https://snapcraft.io/codium) is 1.56.0, which is a few months behind the [latest version](https://github.com/VSCodium/vscodium/releases) (currently 1.59.1). This fact has already been noticed by our users (see https://github.com/VSCodium/vscodium/issues/798).

Is this related to [Travis CI's decision](https://blog.travis-ci.com/oss-announcement) to [move open source project repositories](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/) off of travis-ci.org and onto travis-ci.com?

Can we make this work again? Maybe migrate to GitHub Actions?

### PR DESCRIPTION
**Pull request by lucyllewy**
Exclude any filenames that include `sha1`.

Fixes #11

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Did you mean sha1 OR sha256 sig, or AND?

**Comment by lucyllewy** [comment]
`grep -v` is a negation - so the chaining will remove `sha256` and then remove `sha1` so that neither are in the resultant set of files

**Comment by ghost** [comment]
I wasn't clear enough. You could potentially put these into a single egrep expression and also make sure lowercase/uppercase are covered (to be on the safe side). I was wondering if there is a more robust/encompassing way to sanitize the data.

**Comment by lucyllewy** [comment]
How's that for an improvement?

**Review by ghost — APPROVED** [review]

**Pull request merged**
