### PR TITLE
Try a newer base

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by abitrolly** [comment]
Experiments ended up with this.
```
Failed to generate snap metadata: The specified command 'electron-launch $SNAP/usr/share/codium/bin/codium' defined in the app 'codium' does not exist.
```

**Comment by abitrolly** [comment]
Build works.

**Review by lucyllewy — APPROVED** [review]
LGTM

**Comment by abitrolly** [comment]
I haven't tested that it works. Switching to https://snapcraft.io/docs/gnome-3-38-extension may help to cut the list of dependencies.

**Comment by merlijn-sebrechts** [comment]
PR looks good. Let's merge this and test it in edge to see if it works correctly.

**Comment by abitrolly** [comment]
Can't test this, because download infrastructure is down. https://status.snapcraft.io/

image

**Comment by merlijn-sebrechts** [comment]
Oh, right, that might be why all my tests suddenly fail :sweat_smile: 

image

**Comment by merlijn-sebrechts** [comment]
Issue with the snap store should be fixed.

I'm a bit confused about how this snap gets to the store, since it's not part of Snapcrafters publisher. Is this repo linked to the store?

**Comment by abitrolly** [comment]
No idea. Maybe there is more info through API. https://github.com/VSCodium/vscodium/issues is listed as a contact.

**Pull request merged**
